/**
 * Central site configuration.
 * Update names, contact info, and URLs here — they flow everywhere.
 */

export const siteConfig = {
  name: "GreenBytes",
  tagline: "Smart tech, greener future",
  description:
    "GreenBytes builds lean websites, web apps, automation, and dashboards — fast delivery, clear communication, thoughtful engineering.",
  url: "https://greenbytes.vercel.app", // TODO: replace with real domain when ready
  ogImage: "/og.png", // 1200x630 — will be auto-generated by opengraph-image.tsx

  // Team
  founders: {
    primary: "Het",
    secondary: "Co-founder",
  },

  // Contact
  email: "hello@greenbytes.dev",
  whatsapp: {
    display: "+91 76230 79600",
    // Raw number for wa.me links — only digits, with country code, no +
    raw: "917623079600",
  },
  location: "Gandhinagar, Gujarat · Remote worldwide",

  /**
   * Optional Cal.com booking link.
   * Set to e.g. "https://cal.com/greenbytes/15min" once you've created the account.
   * When null/empty, the booking CTA falls back to opening WhatsApp instead.
   */
  bookingUrl: "" as string,

  // Nav
  nav: [
    { label: "Services", href: "/#services" },
    { label: "Pricing", href: "/pricing" },
    { label: "Projects", href: "/#projects" },
    { label: "Blog", href: "/blog" },
    { label: "About", href: "/#about" },
    { label: "Contact", href: "/#contact" },
  ],
};

/**
 * Build a wa.me URL with a prefilled message.
 * Encodes the message for safe URL transport.
 */
export function buildWhatsAppUrl(message: string): string {
  return `https://wa.me/${siteConfig.whatsapp.raw}?text=${encodeURIComponent(message)}`;
}

/**
 * Returns the booking URL if configured, otherwise falls back to WhatsApp.
 * Lets the "Book a call" CTAs work immediately, even before you set up Cal.com.
 */
export function getBookingUrl(): string {
  if (siteConfig.bookingUrl) return siteConfig.bookingUrl;
  return buildWhatsAppUrl(
    "Hi GreenBytes! I'd like to book a 15-minute discovery call. What times work?"
  );
}
